stages:
  - test
  - build
  - deploy

variables:
  DOCKERHUB_USER: kekishev
  DOCKERHUB_REPOSITORY_NAME: discord-music-bot

test-job:
  stage: test
  image: maven:3.9.13-eclipse-temurin-25
  script:
    - mvn test
  only:
    - merge_requests
    - main

.docker_template:
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker -v
    - docker info
    - docker login docker.io -u "$DOCKERHUB_LOGIN" -p "$DOCKERHUB_PASSWORD"

build-job:
  image: docker:27
  stage: build
  extends: .docker_template
  script:
    - docker build -t $DOCKERHUB_USER/$DOCKERHUB_REPOSITORY_NAME:latest .
    - docker push $DOCKERHUB_USER/$DOCKERHUB_REPOSITORY_NAME:latest
  only:
    - main

.deploy_template:
  image: kroniak/ssh-client:latest
  before_script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
    - >-
      echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile
      /dev/null" > ~/.ssh/config
    - chmod 600 ~/.ssh/id_ed25519

deploy-job:
  image: docker:27
  stage: deploy
  extends: .deploy_template
  script:
    - scp -i ~/.ssh/id_ed25519 docker-compose.yaml root@$SSH_REMOTE_HOST:/root/projects/discord_music_bot/docker-compose.yaml
    - ssh -i ~/.ssh/id_ed25519 root@$SSH_REMOTE_HOST "
      cd /root/projects/discord-music-bot &&
      export DISCORD_MUSIC_BOT_TOKEN=$DISCORD_MUSIC_BOT_TOKEN &&
      docker stop discord-music-bot-backend-1 || true &&
      docker rm discord-music-bot-backend-1 || true &&
      docker image rm $DOCKERHUB_USER/$DOCKERHUB_REPOSITORY_NAME:latest || true &&
      docker pull $DOCKERHUB_USER/$DOCKERHUB_REPOSITORY_NAME:latest &&
      docker compose up -d
      "
  only:
    - main
  when: manual