name: discord-music-bot

services:
  backend:
    image: kekishev/discord-music-bot:latest
    restart: unless-stopped
    ports:
      - "2007:2007"
    environment:
      DISCORD_MUSIC_BOT_TOKEN: ${DISCORD_MUSIC_BOT_TOKEN}
      DISCORD_ADMIN_ID: ${DISCORD_ADMIN_ID}
